version: '3'
services:
  quantum-market-db:
    image: mysql:8
    container_name: quantum-market-db
    restart: always
    ports:
      - 33306:3306
    environment:
      MYSQL_ROOT_PASSWORD: masterpw
      MYSQL_DATABASE: quantum-market
      MYSQL_USER: quantum-market
      MYSQL_PASSWORD: znjsxjaakzpt!@
    volumes:
      - ./db/mysql/data:/var/lib/mysql
      - ./db/mysql/config:/etc/mysql/conf.d
      - ./db/mysql/init:/docker-entrypoint-initdb.d
