spring.application.name: quantum-market-api
spring.profiles.active: local

spring:
  config:
    import:
      - logging.yml
      - db-main.yml

---
spring.config.activate.on-profile: local


---
spring.config.activate.on-profile: staging


---
spring.config.activate.on-profile: prod
